[package]
name = "onda"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "onda"
path = "src/main.rs"

[dependencies]
ropey.workspace = true
onda-core.workspace = true
onda-render.workspace = true
onda-modal.workspace = true
onda-config.workspace = true
onda-syntax.workspace = true
onda-data.workspace = true
onda-agent.workspace = true
onda-dap.workspace = true
onda-lsp.workspace = true
onda-terminal.workspace = true
onda-session.workspace = true
onda-plugin.workspace = true
crossterm.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
regex.workspace = true
toml.workspace = true
nucleo-matcher.workspace = true
ignore.workspace = true
notify.workspace = true

[features]
default = []
debug-overlay = ["onda-render/debug-overlay"]
bench = []

[dev-dependencies]
tempfile.workspace = true
