[package]
name = "onda-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ropey.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
thiserror.workspace = true
smallvec.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
